<?php

return [

    /*
     |----------------------------------------------------------------------------------
     | Log Path
     |----------------------------------------------------------------------------------
     |
     | The path to the directory where log files will be stored.
     | This directory will contain all the log files generated by the application.
     |
     */
    'path' => TMP_PATH . 'log',

    /*
     |-----------------------------------------------
     | Logging Condition
     |-----------------------------------------------
     |
     | Determine if logging should occur.
     | This can only be set to true or false
     |
     */
    'shouldLog' => true,

    /*
     |------------------------------------------------------------------------
     | Log Filename
     |------------------------------------------------------------------------
     |
     | The filename format for the log files.
     | This uses the current date to create a new log file each day.
     |
     */
    'filename' => date('Y-m-d'),

    /*
     |------------------------------------------------------------------------------------------------------------
     | Log Levels
     |------------------------------------------------------------------------------------------------------------
     |
     | Define different log levels for different environments.
     | This allows you to specify the log level (e.g., DEBUG, INFO, WARNING, ERROR) for each environment.
     | The levels are ordered by priority, where DEBUG is the least severe and ERROR is the most severe.
     |
     | Supported levels: DEBUG < INFO < WARNING < ERROR
     |
     */
    'level' => [
        'production'  => 'ERROR',
        'development' => 'DEBUG'
    ]

];
