<?php

return [
    /*
    |--------------------------------------------------------------------------
    | Log Path
    |--------------------------------------------------------------------------
    |
    | The path to the directory where log files will be stored.
    | This directory will contain all the log files generated by the application.
    |
    */
    'path' => DIR_STORAGE . 'log',

    /*
    |--------------------------------------------------------------------------
    | Enable Logging
    |--------------------------------------------------------------------------
    |
    | This option controls whether logging is enabled for the application.
    | You can disable logging entirely by setting this to false.
    |
    */
    'shouldLog' => true,
    /*
    |--------------------------------------------------------------------------
    | Log Filename
    |--------------------------------------------------------------------------
    |
    | The base filename for the log file. If set to null, the logger will
    | automatically use the current date (Y-m-d) as the filename.
    |
    */
    'filename' => null,

    /*
    |--------------------------------------------------------------------------
    | Log File Extension
    |--------------------------------------------------------------------------
    |
    | The file extension to use for log files. Typically this is 'log',
    | but you can customize it to use other extensions like 'txt' or 'json'.
    |
    */
    'extension' => 'log',

    /*
    |--------------------------------------------------------------------------
    | Log Format
    |--------------------------------------------------------------------------
    |
    | The format for each log entry. You can use the placeholders:
    | %datetime%, %level%, and %message%. The placeholders will be replaced
    | with actual log information at runtime.
    |
    */
    'format' => '[%datetime%] [%level%] %message%',

    /*
    |--------------------------------------------------------------------------
    | Default Log Channel
    |--------------------------------------------------------------------------
    |
    | This is the default log channel name used when no specific channel
    | is provided. The final filename will be built using this value
    | along with the current timestamp.
    |
    */
    'default_channel' => 'app',

    /*
    |--------------------------------------------------------------------------
    | Log Levels Per Environment
    |--------------------------------------------------------------------------
    |
    | You may configure the minimum log level for each environment. Messages
    | below the defined level will be ignored. Common levels include:
    | DEBUG, INFO, WARNING, ERROR, CRITICAL, ALERT.
    |
    */
    'logLevel' => [
        'production' => 'ERROR',
        'development' => 'DEBUG',
        'default' => 'WARNING',
    ]
];
